language: cpp
script:
  - cd bin
  - make
compiler: gcc
sudo: required
cache:
  directories:
  - $HOME/.gdal
  - $HOME/.wxwidgets
  - $HOME/.wxpdfdoc
env:
  - WXWIN=$HOME/.wxwidgets
before_install: 
  - chmod +x build/travis/before_install.sh
  - build/travis/before_install.sh
