language: cpp
compiler: gcc
sudo: required
env:
  - WXWIN=$HOME/.wxwidgets
cache:
  directories:
  - $HOME/.gdal
  - $HOME/.wxwidgets
  - $HOME/.wxpdfdoc
install: 
  - chmod +x build/travis/install-dependencies.sh
  - travis_wait 30 build/travis/install-dependencies.sh
before_script:
  - wget -O test-files.tar.gz "https://github.com/terranum-ch/ToolMap-test-files/archive/master.tar.gz"
  - tar -xvzf test-files.tar.gz
  - mv ./ToolMap-test-files-master $HOME/unit_testing
script:
  - cd bin
  - make
