language: cpp
compiler: gcc
dist: trusty
sudo: required
env:
  - WXWIN=$HOME/.wxwidgets
cache:
  directories:
  - $HOME/.gdal
  - $HOME/.wxpdfdoc
  - $HOME/.wxwidgets
  - $HOME/.mysql
install: 
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev
  - sudo apt-get install -y libgeos-dev
  - sudo apt-get install -y libaio-dev
  - sudo apt-get install -y libnuma-dev
  - sudo apt-get install -y libwebkitgtk-dev
  - sudo apt-get install -y libwrap0-dev
  - chmod +x build/travis/build-gdal.sh
  - travis_wait 30 build/travis/build-gdal.sh
  - chmod +x build/travis/build-wxwidgets.sh
  - travis_wait 30 build/travis/build-wxwidgets.sh
  - chmod +x build/travis/build-wxpdfdoc.sh
  - travis_wait build/travis/build-wxpdfdoc.sh
  - chmod +x build/travis/build-mysql.sh
  - travis_wait 30 build/travis/build-mysql.sh
  - chmod +x build/travis/run-cmake.sh
  - build/travis/run-cmake.sh
before_script:
  - sudo apt-get install -y cxxtest
  - wget -q -O test-files.tar.gz "https://github.com/terranum-ch/ToolMap-test-files/archive/master.tar.gz"
  - tar -xzf test-files.tar.gz
  - mv ./ToolMap-test-files-master $HOME/unit_testing
script:
  - cd bin
  - make -j$(nproc)
  - cd test
  - ctest -V
