language: cpp
script: ./configure && make
compiler: gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y gnome-devel
  - sudo apt-get install -y libwxgtk3.0
  - sudo apt-get install -y libwxgtk3.0-dev
  - sudo apt-get install -y libproj-dev
  - sudo apt-get install -y libgeos-dev
  - sudo apt-get install -y libgdal-dev
  - sudo apt-get install -y libmariadbd-dev
  - wget -O wxpdfdoc.tar.gz "https://github.com/utelle/wxpdfdoc/releases/download/v0.9.5/wxpdfdoc-0.9.5.tar.gz"
  - tar -xvzf wxpdfdoc.tar.gz
  - cd wxpdfdoc-0.9.5
  - ./configure --enable-unicode --disable-shared
  - make
  - sudo make install
  - mkdir bin
  - cd bin
  - cmake -DSEARCH_GIS_LIB_PATH=/usr -DMYSQL_MAIN_DIR=/usr -DSEARCH_WXPDFDOCUMENT_PATH=/usr/local -DSEARCH_GEOS=1 -DSEARCH_GDAL=1 ../build