version: 2.6.{build}

image: Visual Studio 2017

cache:
  - projects\libs
  
install:
  # All external dependencies are installed in C:\projects\libs
  - mkdir C:\projects\libs
  - mkdir C:\projects\tmp

  # Install a recent CMake
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\tmp > nul
  - move C:\projects\tmp\cmake-* C:\projects\libs\cmake
  - set PATH=C:\projects\libs\cmake\bin;%PATH%
  - cmake --version
  
  # Install cxxtest
  - set CXXTEST_URL="https://github.com/CxxTest/cxxtest/archive/4.3.zip"
  - appveyor DownloadFile %CXXTEST_URL% -FileName cxxtest.zip
  - 7z x cxxtest.zip -oC:\projects\libs\cxxtest > nul
  - set PATH=C:\projects\libs\cxxtest;%PATH%
  
  # Install wxWidgets
  - mkdir C:\projects\libs\wxwidgets
  - set WX_URL="https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.zip"
  - appveyor DownloadFile %WX_URL% -FileName wxwidgets.zip
  - 7z x wxwidgets.zip -oC:\projects\tmp > nul
  - move C:\projects\tmp\wxWidgets-* C:\projects\tmp\wxwidgets
  - cd C:\projects\tmp\wxwidgets\build\msv
  - nmake -f makefile.vc BUILD=release UNICODE=1 MONOLITHIC=1
  - move C:\projects\tmp\wxwidgets\include C:\projects\libs\wxwidgets\include
  - move C:\projects\tmp\wxwidgets\lib\vc_lib\mswu\wx\setup.h C:\projects\libs\wxwidgets\include\wx\setup.h
  - move C:\projects\tmp\wxwidgets\lib\vc_lib\mswu\wx\msw\rcdefs.h C:\projects\libs\wxwidgets\include\wx\msw\rcdefs.h
  - move C:\projects\tmp\wxwidgets\lib C:\projects\libs\wxwidgets\lib
  
build_script:
  - echo Running cmake...
  - dir
  - mkdir bin
  - cd bin
  - cmake -G "Visual Studio 15 2017 Win64" -DSEARCH_GIS_LIB_PATH=C:\projects\libs\gdal -DSEARCH_GEOS_LIB_PATH=C:\projects\libs\geos -DSEARCH_CURL_LIB_PATH=C:\projects\libs\curl -DMYSQL_MAIN_DIR=C:\projects\libs\mysql -DSEARCH_WXPDFDOCUMENT_PATH=C:\projects\libs\wxpdfdoc -DSEARCH_GEOS=1 -DSEARCH_GDAL=1 ../code/build cmake --build . --config relwithdebinfo -DUSE_UNITTEST=1 -DCXXTEST_INCLUDE_DIR=C:\lib\cxxtest -DCXXTEST_PYTHON_TESTGEN_EXECUTABLE=C:\lib\cxxtest\bin\cxxtestgen
