version: 2.6.{build}

image: Visual Studio 2017

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  WXWIN: C:\projects\libs\wxwidgets

  # multiprocessor compilation
  CFLAGS: /MP
  CXXFLAGS: /MP
  
cache:
  - C:\projects\libs
  
install:
  - ps: build/appveyor/install.ps1
  
build_script:
  - echo Running cmake...
  - cd C:\projects\toolmap
  - mkdir bin
  - cd bin
  - cmake -G "Visual Studio 15 2017 Win64" -DSEARCH_GDAL_PATH=C:\projects\libs\gdal -DSEARCH_GEOS_PATH=C:\projects\libs\geos -DSEARCH_PROJ_PATH=C:\projects\libs\proj -DSEARCH_CURL_PATH=C:\projects\libs\curl -DMYSQL_MAIN_DIR=C:\projects\libs\mysql -DSEARCH_WXPDFDOCUMENT_PATH=C:\projects\libs\wxpdfdoc -DSEARCH_GEOS=1 -DSEARCH_GDAL=1 -DUSE_UNITTEST=1 -DCXXTEST_INCLUDE_DIR=C:\projects\libs\cxxtest -DCXXTEST_PYTHON_TESTGEN_EXECUTABLE=C:\projects\libs\cxxtest\bin\cxxtestgen ..
  - cmake --build . --config relwithdebinfo > nul

test_script:
  - cd C:\projects\toolmap\bin\test
  - ctest -V

after_test:
  - cd C:\projects\toolmap\bin
  - cpack -C relwithdebinfo
  - cpack -C relwithdebinfo -G ZIP
  - cd C:\projects\toolmap
  - copy bin\*Setup.exe .\
  - copy bin\*Setup.zip .\

artifacts:
  - path: '*Setup.exe'
    name: ToolMapInstaller
    type: file

  - path: '*Setup.zip'
    name: ToolMapInstallerZip
    type: zip

deploy:
  - provider: FTP
    protocol: ftp
    host: euso.ftp.infomaniak.com
    username: euso_toolmap
    password:
      secure: WWmGrLRonuGbVQ8y6bvsmCQha3YggTiPsAAs0egS/g0=
    artifact: 
    on:
      branch: nightly
    